fix: Integration Tests in tests.yml (Funnel install)
Signed-off-by: Liam Beckman <lbeckman314@gmail.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -52,13 +52,33 @@ jobs:
             --cov-fail-under=99 \
             --ignore=tests/integration
 
+      # Note: Using the same install steps here as in nf-ga4gh plugin
+      # https://github.com/nextflow-io/nf-ga4gh/blob/1.4.1/.github/workflows/build.yml#L78-L101
+      - name: Install TES Server
+        run: |
+          # Pinning install script below to stable commit for security/reproducibility
+          # Ref: https://docs.github.com/en/actions/reference/security/secure-use#using-third-party-actions
+          # Release: https://github.com/calypr/funnel/releases/tag/v0.11.8
+
+          INSTALL_SCRIPT=https://raw.githubusercontent.com/calypr/funnel/4103475e492dec1fd853e9863d0caad15fc504c0/install.sh
+          curl -fsSL $INSTALL_SCRIPT | bash -s -- v0.11.8
+
+      - name: Start TES Server
+        run: |
+          set -euo pipefail
+          nohup funnel server run > funnel.log 2>&1 &
+          echo $! > funnel.pid
+          for i in $(seq 1 10); do
+            if curl -fsS http://localhost:8000/service-info >/dev/null 2>&1; then
+              echo "Funnel server started"
+              exit 0
+            fi
+            sleep 1
+          done
+          echo "Funnel server failed to start!"
+          cat funnel.log
+          exit 1
+
       - name: Run integration tests
         run: |
-          /bin/bash -c "$(curl -fsSL https://github.com/calypr/funnel/releases/latest/download/install.sh)"
-          funnel --version
-          funnel server --LocalStorage.AllowedDirs $HOME run &
-          for i in $(seq 1 20); do
-+            curl -fsS http://localhost:8000/ga4gh/tes/v1/service-info && break
-+            sleep 1
-+          done
           pytest tests/integration
